require "./spec_helper"

# without_2 = %q[<section class="level-0 non-meta outline" id="4"><h2><a title="Permanent link" href="#4">4.</a></h2>The admissibility of a case or the jurisdiction of the Court may be challenged only once by any person or State referred to in paragraph 2. The challenge shall take place prior to or at the commencement of the trial. In exceptional circumstances, the Court may grant leave for a challenge to be brought more than once or at a time later than the commencement of the trial. Challenges to the admissibility of a case, at the commencement of a trial, or subsequently with the leave of the Court, may be based only on <a data-toggle="tooltip" title="Issues of admissibility" href="article_17_issues_of_admissibility">article 17</a>, paragraph 1 (c).</section>]
# with_2___ = %q[<section class="level-0 non-meta outline" id="4"><h2><a title="Permanent link" href="#4">4.</a></h2>The admissibility of a case or the jurisdiction of the Court may be challenged only once by any person or State referred to in paragraph 2. The challenge shall take place prior to or at the commencement of the trial. In exceptional circumstances, the Court may grant leave for a challenge to be brought more than once or at a time later than the commencement of the trial. Challenges to the admissibility of a case, at the commencement of a trial, or subsequently with the leave of the Court, may be based only on <a data-toggle="tooltip" title="Issues of admissibility" href="article_17_issues_of_admissibility#1-c">article 17, paragraph 1 (c)</a>.</section>]

describe PinpointXref do
  describe ".add_pinpoint" do
    without = %q[<section class="level-0 non-meta outline" id="2"><h2><a title="Permanent link" href="#2">2.</a></h2>If a State becomes a Party to this Statute after its entry into force, the Court may exercise its jurisdiction only with respect to crimes committed after the entry into force of this Statute for that State, unless that State has made a declaration under <a data-toggle="tooltip" title="Preconditions to the exercise of jurisdiction" href="article_12_preconditions_to_the_exercise_of_jurisdiction">article 12</a>, paragraph 3.</section>]
    with___ = %q[<section class="level-0 non-meta outline" id="2"><h2><a title="Permanent link" href="#2">2.</a></h2>If a State becomes a Party to this Statute after its entry into force, the Court may exercise its jurisdiction only with respect to crimes committed after the entry into force of this Statute for that State, unless that State has made a declaration under <a data-toggle="tooltip" title="Preconditions to the exercise of jurisdiction" href="article_12_preconditions_to_the_exercise_of_jurisdiction#3">article 12, paragraph 3</a>.</section>]

    PinpointXref.add_pinpoint(without).should eq with___
  end
end
